### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by KathanP19** [neex/gifoeb#6]
Command : `./gifoeb recover test.jpg `
Output: 
```
Traceback (most recent call last):
  File "./gifoeb", line 259, in <module>
    palette = recover(load_picture(pict_data, tool=args.tool), colors=args.colors)
  File "./gifoeb", line 133, in load_picture
    identify = subprocess.Popen(prefix + ['identify', '-format', '%w %h', '-[{}]'.format(picture_index)], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by neex** [comment]
I believe you don't have ImageMagick installed, which is a dependency for this program.
