### ISSUE TITLE
Error Occured while dumping 

### ISSUE THREAD

**Issue by 0xh7ml** [neex/gifoeb#7]
Traceback (most recent call last):
  File "./gifoeb", line 245, in <module>
    gif = gen_dumping_gif(w, h, tool=args.tool, animate=args.animate, colors=args.colors)
  File "./gifoeb", line 110, in gen_dumping_gif
    convert = subprocess.Popen(command, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'convert'

**Comment by neex** [comment]
It looks like you don't have ImageMagick properly set up on your local machine.
